version: '3'
services:


  database:
    container_name: 'database'
    image: mysql:8.0.36
    environment:
      MYSQL_ROOT_PASSWORD: Jagusiek31
      MYSQL_DATABASE: memes
    ports:
      - "3306:3306"

  app:
    build:
      context: .
      dockerfile: Dockerfile_webapp
    ports:
      - "8080:8080"
    depends_on:
      - database